export const DASHBOARD_ACTIONS = {
  GET_SUMMARY: "DASHBOARD_ACTIONS/GET_SUMMARY",
} as const;

export const PRODUCT_ACTIONS = {
  GET_ALL: "PRODUCT_ACTIONS/GET_ALL",
  GET_BY_ID: "PRODUCT_ACTIONS/GET_BY_ID",
  CREATE: "PRODUCT_ACTIONS/CREATE",
  UPDATE: "PRODUCT_ACTIONS/UPDATE",
  DELETE: "PRODUCT_ACTIONS/DELETE",
} as const;

export const MACHINE_ACTIONS = {
  GET_ALL: "MACHINE_ACTIONS/GET_ALL",
  GET_BY_ID: "MACHINE_ACTIONS/GET_BY_ID",
  CREATE: "MACHINE_ACTIONS/CREATE",
  UPDATE: "MACHINE_ACTIONS/UPDATE",
  UPDATE_STATUS: "MACHINE_ACTIONS/UPDATE_STATUS",
} as const;

export const WORK_ORDER_ACTIONS = {
  GET_ALL: "WORK_ORDER_ACTIONS/GET_ALL",
  GET_BY_ID: "WORK_ORDER_ACTIONS/GET_BY_ID",
  CREATE: "WORK_ORDER_ACTIONS/CREATE",
  UPDATE: "WORK_ORDER_ACTIONS/UPDATE",
  UPDATE_STATUS: "WORK_ORDER_ACTIONS/UPDATE_STATUS",
  RECORD_OUTPUT: "WORK_ORDER_ACTIONS/RECORD_OUTPUT",
} as const;

export const QUALITY_CHECK_ACTIONS = {
  GET_ALL: "QUALITY_CHECK_ACTIONS/GET_ALL",
  CREATE: "QUALITY_CHECK_ACTIONS/CREATE",
} as const;

export const INVENTORY_ACTIONS = {
  GET_STOCK_SUMMARY: "INVENTORY_ACTIONS/GET_STOCK_SUMMARY",
  GET_TRANSACTIONS: "INVENTORY_ACTIONS/GET_TRANSACTIONS",
  CREATE_TRANSACTION: "INVENTORY_ACTIONS/CREATE_TRANSACTION",
} as const;

export const BOM_ACTIONS = {
  GET: "BOM_ACTIONS/GET",
  ADD_ITEM: "BOM_ACTIONS/ADD_ITEM",
  UPDATE_ITEM: "BOM_ACTIONS/UPDATE_ITEM",
  DELETE_ITEM: "BOM_ACTIONS/DELETE_ITEM",
  SET: "BOM_ACTIONS/SET",
} as const;
